### ISSUE TITLE
Incorrect error message for sizeof(double complex)

### ISSUE THREAD

**Issue by jrenaud90** [ktnrg45/cyright#3]
**Describe the bug**
Using `double complex` type with `sizeof()` function raises " "(" was not closed " even though the usage is correct. 

**To Reproduce**
When using [vs-code-cython](https://github.com/ktnrg45/vs-code-cython):

```cython
from cpython.mem cimport PyMem_Malloc
cdef double complex* ptr = <double complex *> PyMem_Malloc(10 * sizeof(double complex))
```

![image](https://github.com/ktnrg45/cyright/assets/6547310/2cccd154-26ef-41c3-bba1-f75ed1b7e605)

**Expected behavior**
This usage is correct, no IDE should be raised.

**VS Code extension or command-line**
Cython VS Code: Version v0.3.10
VS Code: Version v1.82.3

**Comment by ktnrg45** [comment]
Thanks for reporting this. The issue has been fixed in cythonV2.
